# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editBoxWindow(object):

    def setupUi(self, newBoxWindow):
        newBoxWindow.setObjectName("newBoxWindow")
        newBoxWindow.resize(257, 246)
        self.formLayout = QtWidgets.QFormLayout(newBoxWindow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(newBoxWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.boxNumberInput = QtWidgets.QLineEdit(newBoxWindow)
        self.boxNumberInput.setObjectName("boxNumberInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.boxNumberInput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(newBoxWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.shelfNumberInput = QtWidgets.QLineEdit(newBoxWindow)
        self.shelfNumberInput.setObjectName("shelfNumberInput")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.shelfNumberInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.cancelButton = QtWidgets.QPushButton(newBoxWindow)
        self.cancelButton.setObjectName("cancelButton")
        self.saveBoxButton = QtWidgets.QPushButton(newBoxWindow)
        self.saveBoxButton.setObjectName("saveBoxButton")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.saveBoxButton)
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.cancelButton)
        self.deleteButton = QtWidgets.QPushButton(newBoxWindow)
        self.deleteButton.setObjectName("deleteButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.deleteButton)

        self.retranslateUi(newBoxWindow)
        QtCore.QMetaObject.connectSlotsByName(newBoxWindow)

    def retranslateUi(self, newBoxWindow):
        _translate = QtCore.QCoreApplication.translate
        newBoxWindow.setWindowTitle(_translate("newBoxWindow", "Dialog"))
        self.label.setText(_translate("newBoxWindow", "Box Number:"))
        self.label_2.setText(_translate("newBoxWindow", "Shelf Number:"))
        self.cancelButton.setText(_translate("newBoxWindow", "Cancel"))
        self.saveBoxButton.setText(_translate("newBoxWindow", "Save"))
        self.deleteButton.setText(_translate("newBoxWindow", "Delete"))