# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newBoxWindow(object):
    
    def setupUi(self, newBoxWindow):
        newBoxWindow.setObjectName("newBoxWindow")
        newBoxWindow.resize(257, 246)
        self.formLayout = QtWidgets.QFormLayout(newBoxWindow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(newBoxWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.manualRadioButton = QtWidgets.QRadioButton(newBoxWindow)
        self.manualRadioButton.setObjectName("manualRadioButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.manualRadioButton)
        self.autoGenRadioButton = QtWidgets.QRadioButton(newBoxWindow)
        self.autoGenRadioButton.setObjectName("autoGenRadioButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.autoGenRadioButton)
        self.boxNumberInput = QtWidgets.QLineEdit(newBoxWindow)
        self.boxNumberInput.setObjectName("boxNumberInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.boxNumberInput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.label_2 = QtWidgets.QLabel(newBoxWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.shelfNumberInput = QtWidgets.QLineEdit(newBoxWindow)
        self.shelfNumberInput.setObjectName("shelfNumberInput")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.shelfNumberInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.cancelButton = QtWidgets.QPushButton(newBoxWindow)
        self.cancelButton.setObjectName("cancelButton")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.cancelButton)
        self.addBoxButton = QtWidgets.QPushButton(newBoxWindow)
        self.addBoxButton.setObjectName("addBoxButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.addBoxButton)

        self.retranslateUi(newBoxWindow)
        QtCore.QMetaObject.connectSlotsByName(newBoxWindow)

    def retranslateUi(self, newBoxWindow):
        _translate = QtCore.QCoreApplication.translate
        newBoxWindow.setWindowTitle(_translate("newBoxWindow", "New Box"))
        self.label.setText(_translate("newBoxWindow", "Box Number:"))
        self.manualRadioButton.setText(_translate("newBoxWindow", "Manually"))
        self.autoGenRadioButton.setText(_translate("newBoxWindow", "Auto Generate"))
        self.label_2.setText(_translate("newBoxWindow", "Shelf Number:"))
        self.cancelButton.setText(_translate("newBoxWindow", "Cancel"))
        self.addBoxButton.setText(_translate("newBoxWindow", "Add Box"))
